spring:
  data:
    mongodb:
      database: Task
      uri: mongodb+srv://admin:admin@cluster0.90baew0.mongodb.net/?retryWrites=true&w=majority
  application:
    name: product-service

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
